blog/urls.py
from django.urls import path
from . import views


app_name = "blog"

urlpatterns = [
    # представления поста
    path('search/', views.post_search, name='post_search'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/',
      views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
     path('<int:post_id>/comment/',
         views.post_comment, name='post_comment'),
]

blojec/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path("api/", include("blog_api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )
    

    objects = models.Manager()  # менеджер, применяемый по умолчанию
    published = PublishedManager()  # пользовательский менеджер
    tags = TaggableManager() # менеджер тэгов


    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий {self.name} на {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        required=True,
        label="Имя",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-1", "placeholder": "Ваше Имя"}
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-control mb-1", "placeholder": "E-Mail"}
        ),
    )
    to = forms.EmailField(
        required=True,
        label="Кому",
        widget=forms.TextInput(
            attrs={"class": "form-control mb-1", "placeholder": "Кому отправить"}
        ),
    )
    comments = forms.CharField(
        required=False,
        label="Комментарий",
        widget=forms.Textarea(
            attrs={"class": "form-control mb-1", "placeholder": "Ваш комментарий"}
        ),
    )


class CommentForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        label="Имя",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Ваше Имя"}
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Email"}
        ),
    )
    body = forms.CharField(
        required=True,
        label="Текст",
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Ваш комментарий"}
        ),
    )

    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control mb-1",
                "placeholder": "Введите форазу для поиска...",
            }
        )
    )

blog/views.py
from re import search
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from taggit.models import Tag
from django.core.mail import send_mail
from django.conf import settings
from blojec import settings
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def post_share(request, post_id):
    # Извлечь пост по его идентификатору id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} рекомендует Вам прочитать " f"{post.title}"
            message = (
                f"Прочтите {post.title} по адресу {post_url}\n\n"
                f"{cd['name']} ({cd['email']}) комментирует: {cd['comments']}"
            )
            send_mail(subject, message, settings.EMAIL_HOST_USER, [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_list(request, tag_slug=None):
    post_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags=tag)

    # Постраничная разбивка по 3 на страницу
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # Если page_number не целое число, то
        # выдать первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если page_number находится вне диапазона, то
        # выдать последнюю страницу результатов
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html", {"posts": posts, "tag": tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Список активных комментариев к этому посту
    comments = post.comments.filter(active=True)

    # Форма для комментариев пользователей
    form = CommentForm()

    # Список схожих постов
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(
        request,
        "blog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body', config='russian')
            search_query = SearchQuery(query, config='russian')
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    
    return render(request, 'blog/post/search.html', 
                  {'form': form, 'query': query, 'results': results})

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {# Load the django_bootstrap5 library #}
    {% load django_bootstrap5 %}

    {# Load CSS and JavaScript separately#}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">МОЙ БЛОДЖЕК</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users-profile' %}"><img
                            class="rounded-circle" width="30" src="{{ user.profile.avatar.url }}"/> {{ user.username }}
                    </a></li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post">{% csrf_token %}
                            <a href="#" class="nav-link" onclick="parentNode.submit();">Выйти</a>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="container d-flex align-items-center justify-content-center">
                        <div class="alert alert-warning alert-dismissible fade show w-50  d-block" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
        <!-- Widgets-->
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-header">Это мой блоДжек.</div>
                <div class="card-body">
                    Опубликовано постов {% total_posts %} шт.
                </div>
            </div>
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Поиск</div>
                <div class="card-body">
                    <div class="input-group">
                        <form action="/search/" method="get" class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Введите фразу для поиска..."
                                   required="" id="id_query">
                            <button class="btn btn-primary" id="button-search" type="submit">Искать!</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Latest posts widget-->
            <div class="card mb-4">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action active" aria-current="true">
                        Свежие публикации
                    </a>
                    {% show_latest_posts 3 %}
                </div>
            </div>
            <div class="card mb-4">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action active" aria-current="true">
                        Самые популярные публикации
                    </a>
                    {% get_most_commented_posts as most_commented_posts %}
                    {% for post in most_commented_posts %}
                        <a class="list-group-item list-group-item-action"
                           href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer-->
<footer class="py-5 bg-dark mt-2 mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; МойБлоджек 2025, Powered by
        Django</p></div>
</footer>
</body>
</html>



{% comment %} <body>
<div id="content">
    {% if messages %}
        {% for message in messages %}
            {{ message.tags }} {{ message }}
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>Мой БлоДжек</h2>
    <p>Это мой бложек.
       Опубликовано постов: {% total_posts %} шт.
    </p>
    <hr>
    {% if user.is_authenticated %}
        Привет, {{ user.username }}!
        <p><a href="{% url 'users-profile' %}">Мой профиль</a></p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <a href="#" onclick="parentNode.submit();">Выйти</a>
        </form>
    {% else %}
        <p>Вы не авторизованы</p>
        <p>
            <a href="{% url 'login' %}">Войти</a> | 
            <a href="{% url 'signup' %}">Регистрация</a>
        </p>
        <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p>
    {% endif %}
    <hr>
    <h3>Свежие публикации</h3>
    {% show_latest_posts 5 %}

      <h3>Самые популярные публикации</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
         {% for post in most_commented_posts %}
         <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
         </li>
         {% endfor %}
      </ul>
</div>
</body>
</html> {% endcomment %}